version: "3"
services:
  vele_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SOCKET: "/var/lib/mysql/mysql.sock"
      MYSQL_HOST: vele_db
  
  vele_redis:
    image: redis:alpine
    ports:
      - "6379:6379"